version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - "8000:80"
    networks:
      - app-network
    environment:
      APP_ENV: development
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: news_aggregator
      MYSQL_USER: news_app
      MYSQL_PASSWORD: news123
      MYSQL_ROOT_PASSWORD: news123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: 
    driver: local
